# Generated by Django 5.2.15 on 2026-07-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brief_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
