# Generated by Django 5.2.15 on 2026-07-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_brief_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_discounted",
            field=models.BooleanField(default=False),
        ),
    ]
