# Generated by Django 5.2.15 on 2026-07-08 17:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_user_phone_number_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format +989xxxxxxxxx",
                        regex="^\\+989\\d{9}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="default/avatar.png", upload_to="profile_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
