# Generated by Django 5.2.15 on 2026-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0012_alter_profile_description_alter_profile_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="default/avatar.png", upload_to="profile_picture"
            ),
        ),
    ]
