# Generated by Django 5.2.15 on 2026-07-20 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format +989xxxxxxxxx",
                        regex="^\\+989\\d{9}$",
                    )
                ],
            ),
        ),
    ]
