# Generated by Django 5.2.15 on 2026-09-13 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_emailverificationtoken_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
