# Generated by Django 5.2.15 on 2026-08-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_order_address_order_city_order_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="max_usage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
