# Generated by Django 5.2.15 on 2026-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_remove_order_address_remove_order_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="address_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
