# Generated by Django 5.2.15 on 2026-08-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_useraddress_address_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponusage",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="order.coupon",
            ),
        ),
    ]
