# Generated by Django 5.2.15 on 2026-08-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_couponusage_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="tax_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "در انتظار پرداخت"),
                    (2, "پرداخت شده"),
                    (3, "در حال پردازش"),
                    (4, "ارسال شده"),
                    (5, "تحویل داده شده"),
                    (6, "لغو شده"),
                ],
                default=1,
            ),
        ),
    ]
