# Generated by Django 5.2.15 on 2026-07-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Contact us"},
        ),
    ]
