# Generated by Django 5.2.15 on 2026-08-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="tax_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
