# Generated by Django 5.2.15 on 2026-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_tax_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("success", "پرداخت موفق"),
                    ("failed", "پرداخت ناموفق"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
